name: homii
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  device_preview: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/homii_icon.png
    - assets/images/food_illustrations.png
    - assets/images/food_corner.png
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
    - assets/images/apple_icon.png
    - assets/images/recipes/
    - assets/images/recipes/breakfast_skillet_image.png
    - assets/images/recipes/creamy_yogurt_image.png
    - assets/images/recipes/duck_orange_image.png
    - assets/images/recipes/garlic_chicken_image.png
    - assets/images/recipes/ginger_fish_image.png
    - assets/images/recipes/onion_carbonara_image.png
    - assets/images/recipes/oven_risotto_image.png
    - assets/images/recipes/roasted_duck_image.png
    - assets/images/recipes/roast_potatoes_image.png
    - assets/images/recipes/salmon_croquettes_image.png
    - assets/images/cart/milk_image.png
    - assets/images/cart/egg_image.png
    - assets/images/cart/bread_image.png
    - assets/images/cart/mushrooms_image.png
