name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' 

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app